[package]
name = "test_channel_block"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35.1", features = ["full", "tracing"] }
once_cell = "1.7.2"
console-subscriber = "0.2.0"
flume = "0.11.0"

[build]
rustflags = ["--cfg", "tokio_unstable"]
